# achimate-docs/antora-playbook.yml
site:
  title: Руководство по ArchiMate
  url: https://eustatos.github.io/archimate-docs
content:
  sources:
    - url: ./ 
      branches: HEAD
      start_path: docs
asciidoc:
  attributes:
    experimental: ''
    sectanchors: ''
    toc: macro
    toclevels: 3
    source-highlighter: highlightjs
    highlightjs-theme: github
    icons: font
    idprefix: ''
    idseparator: '-'
output:
  dir: ./build/site
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true